{% set version = "0.8.0" %}

package:
  name: bambi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bambi/bambi-{{ version }}.tar.gz
  sha256: 8f21acbe8422c4e9eba935e2887fb95436ff10d60abded1233dbbb98c6bc2364

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - arviz >=0.11.2
    - formulae ==0.3.4
    - numpy >=1.16.1,<1.22.0
    - pandas >=1.0.0
    - pymc3 >=3.9.0
    - scipy >=1.7.0
    - statsmodels >=0.9

test:
  imports:
    - bambi
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/bambinos/bambi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: BAyesian Model Building Interface in Python

extra:
  recipe-maintainers:
    - ocefpaf
