{% set version = "0.9.2" %}

package:
  name: bambi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bambi/bambi-{{ version }}.tar.gz
  sha256: 53ad37836dd7ca91b86da05c0f149e96e48fa29598ef01d9c8a5d6c300b8f973

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - arviz >=0.11.2
    - formulae ==0.3.4
    - numpy >1.22
    - pandas >=1.0.0
    - pymc >=4.0.0
    - scipy >=1.7.0
    - setuptools >47.1.0

test:
  imports:
    - bambi
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/bambinos/bambi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: BAyesian Model Building Interface in Python

extra:
  recipe-maintainers:
    - ocefpaf
