{% set version = "0.2.0" %}

package:
  name: bambi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bambi/bambi-{{ version }}.tar.gz
  sha256: 2d1521905f282992ea7e6bfc5e36fbe82399c7b8cf0f94d236fccfc89095dc61

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - arviz >=0.6.1
    - numpy >=1.16.1
    - pandas >=1.0.0
    - patsy >=0.5.1
    - pymc3 >=3.8
    - pystan >=2.18.0.0
    - statsmodels >=0.9

test:
  imports:
    - bambi
  commands:
    - pip check
  requires:
    - pip


about:
  home: http://github.com/bambinos/bambi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: BAyesian Model Building Interface in Python

extra:
  recipe-maintainers:
    - ocefpaf
