{% set name = "bambi" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bambi-{{ version }}.tar.gz
  sha256: c6528870d2164515205870fa75cbf89b3c684f7a81023e3bff205058c771f9c1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - pytensor >=2.12.1
    - python >=3.8
    - arviz >=0.12.0
    - formulae >=0.4.0
    - python-graphviz
    - numpy >1.22
    - pandas >=1.0.0
    - pymc >=5.4.0
    - scipy >=1.7.0
    - setuptools >47.1.0

test:
  imports:
    - bambi
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/bambinos/bambi
  summary: BAyesian Model Building Interface in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
