{% set version = "0.4.0" %}

package:
  name: bambi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bambi/bambi-{{ version }}.tar.gz
  sha256: 80f237e2bd5b9252e1cb95ccb5b84ca22d38e3272f1469014598f9063c71e4c8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pandas
    - patsy
    - pymc3
    - statsmodels
    - matplotlib-base

test:
  imports:
    - bambi
    - bambi.backends
    - bambi.external

about:
  home: http://github.com/bambinos/bambi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: BAyesian Model Building Interface in Python

extra:
  recipe-maintainers:
    - ocefpaf
