{% set name = "bambi" %}
{% set version = "0.16.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bambi-{{ version }}.tar.gz
  sha256: ca3d1f1fc9523328e4e8c96a1ae0a019380e39abb33afc4b014bc7dd5c50ae88

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - arviz >=0.20.0
    - formulae >=0.5.3
    - python-graphviz
    - numpy >1.22
    - pandas >=1.0.0
    - pymc >=5.26.1
    - pytensor >=2.12.3
    - scipy >=1.7.0
    - setuptools >47.1.0

test:
  imports:
    - bambi
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: http://github.com/bambinos/bambi
  summary: BAyesian Model Building Interface in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
