{% set version = "0.5.0" %}

package:
  name: bambi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bambi/bambi-{{ version }}.tar.gz
  sha256: 76b52b82503fb110af08bbed1d53a4ec140a938260fc8a7c13f5816fd3f5ff0a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - arviz >=0.10.0
    - formulae >=0.0.9
    - numpy >=1.16.1
    - pandas >=1.0.0
    - pymc3 >=3.9.0
    - statsmodels >=0.9

test:
  imports:
    - bambi
    - bambi.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/bambinos/bambi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: BAyesian Model Building Interface in Python

extra:
  recipe-maintainers:
    - ocefpaf
