{% set name = "bambi" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bambi-{{ version }}.tar.gz
  sha256: b4c432234f531fbceec7722535ca5bad73926433b2f78b3c101b00410d8f062d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8
    - arviz >=0.12.0
    - formulae >=0.5.0
    - python-graphviz
    - numpy >1.22
    - pandas >=1.0.0
    - pymc >=5.5.0
    - pytensor >=2.12.3
    - scipy >=1.7.0
    - setuptools >47.1.0

test:
  imports:
    - bambi
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/bambinos/bambi
  summary: BAyesian Model Building Interface in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
