{% set version = "0.7.1" %}

package:
  name: bambi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bambi/bambi-{{ version }}.tar.gz
  sha256: d57401326528f40ed78d6759723ee554581f6940c566263d6c176283f5428cf7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - arviz >=0.11.2
    - formulae ==0.2.0
    - numpy >=1.16.1,<1.22.0
    - pandas >=1.0.0
    - pymc3 >=3.9.0
    - scipy >=1.7.0
    - statsmodels >=0.9

test:
  imports:
    - bambi
    - bambi.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/bambinos/bambi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: BAyesian Model Building Interface in Python

extra:
  recipe-maintainers:
    - ocefpaf
