{% set name = "bambi" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bambi-{{ version }}.tar.gz
  sha256: b2ced9433afdd60f2dfc37769dcc3bf116baaa34ff6c34126baefad13fe8351e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - arviz >=0.11.2
    - formulae ==0.3.4
    - numpy >1.22
    - pandas >=1.0.0
    - pymc >=5.0.0
    - scipy >=1.7.0
    - setuptools >47.1.0

test:
  imports:
    - bambi
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/bambinos/bambi
  summary: BAyesian Model Building Interface in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
