schema_version: 1

context:
  name: bambi
  version: "0.16.0"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/bambi-${{ version }}.tar.gz
  sha256: ca3d1f1fc9523328e4e8c96a1ae0a019380e39abb33afc4b014bc7dd5c50ae88

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - setuptools-scm >=8
    - pip
  run:
    - python >=${{ python_min }}
    - arviz >=0.20.0
    - formulae >=0.5.3
    - python-graphviz
    - pandas >=1.0.0
    - pymc >=5.26.1

tests:
  - python:
      imports:
        - bambi
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.*

about:
  summary: BAyesian Model Building Interface in Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/bambinos/bambi

extra:
  recipe-maintainers:
    - ocefpaf
