schema_version: 1

context:
  name: bambi
  version: "0.21.0"
  python_min: '3.12'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/56/8e/101a4ab5a9f9e41ba0b2a69590303617e11e123b78f0e56191b04c631ae1/bambi-${{ version }}.tar.gz
  sha256: 68c096406d9426c2d244512b373c2f3b0123a553faf22ddf500b2a2400b60e85

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - setuptools-scm >=8
    - pip
  run:
    - python >=${{ python_min }}
    - formulae >=0.6.0,<0.7.0
    - python-graphviz
    - pandas >=1.0.0
    - pymc >=6.0.0,<7.0.0
    - matplotlib-base >=3.9.0
    - sparse >=0.17.0,<0.18
    - arviz-plots >=1.0.0,<2.0.0
    - pytensor >=3.0.0,<4.0.0
    - seaborn >=0.13.2,<0.14
tests:
  - python:
      imports:
        - bambi
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: BAyesian Model Building Interface in Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/bambinos/bambi

extra:
  recipe-maintainers:
    - ocefpaf
