travis:
  secure:
    BINSTAR_TOKEN: M0l8FtKxZoEmVPteZQziwsCE0j24i4TTWhxJJ0wXpoE2ZrCtvurcNbSm+jmlk6Cff1eXRgMtnhuwald4NIEB7m6KtN7DKzrmTggthDDtFZKBoy34FltJzuA3N4s93xNeL2Fo7Co3R57JjGQEOR0PvVSIt0te4uibqwY6wbt4ae4mjN6lQJbMksKYNr/vpao3Wk1UOs8RQG83ZwYpguq4h6fFxJ7hHqcHZ4HxmB3n4cUHFKfaE2Rq8Srbia8M8NjwvxpvggN3VDRzMZOO+hnuERf+Bf4pk2hBXlvis3kd7+rtVcHWoOrZzTQMgy1p8utUJcQeET1c2QVBPNQDMjoSbg1P396m8FDkrCivrZOWLmOsYFh43X3c0HHUJ+pYfNwgTuxqzTRwFTJO3Rzc/3dQ9jTGJlTOWsVNlhr+B/O8YRwDmBJXjQ3xzuHQzuDnrmj6Bj7cIq1avxYcX9AGoEu2aXMUHFEjs09GQjjo+T6K+wGJw1f7b+JzmymnPmIkqbhWl0rIkfX5pdLyWe9QXC8cpEr+Edpr67IFVqWR/Jcekt+VQBdvuDSb2bchFi4TOBGrHVK0jABq+zgFzqAnE9R3mVObHyrUJ0mcN6DxSSK8tlJKEeRRzcu11iPsuEXVkXEpqNyKP7jg5N1EKfLZiMWW7exQiOW+COkjzF9+ixXl228=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
